{% set name = "kedro" %}
{% set version = "0.18.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro-{{ version }}.tar.gz
  sha256: da219eaf10ed96909195dda53cb33c66a3e017012501d08f0da90ce1879a3364

build:
  skip: True  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  entry_points:
    - kedro = kedro.framework.cli:main
  number: 0
  script_env:
   - PYTHONWARNINGS="ignore::UserWarning"

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - anyconfig >=0.10.0
    - attrs >=21.3
    - python-build >=0.7.0
    - cachetools >=4.1
    - click >=4.0
    - cookiecutter >=2.1.1,<3.0
    - dynaconf >=3.1.2,<4.0
    - fsspec >=2021.4
    - gitpython >=3.0
    - importlib-metadata >=3.6,<7.0.0
    - importlib_resources >=1.3,<7.0.0
    - jmespath >=0.9.5
    - more-itertools >=8.14.0
    - omegaconf >=2.1.1
    - parse >=1.19.0
    - pip-tools >=6.5
    - pluggy >=1.0
    - pyyaml >=4.2,<7.0
    - rich >=12.0,<14.0
    - rope >=0.21,<2.0
    - setuptools >=65.5.1
    - toml >=0.10.0
    - toposort >=1.5

test:
  imports:
    - kedro
  commands:
    - kedro --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumblacklabs/kedro
  summary: A Python library that implements software engineering best-practice for data and ML pipelines.
  license_family: Apache
  license: Apache-2.0
  license_file: LICENSE.md
  doc_url: https://docs.kedro.org
  dev_url: https://github.com/quantumblacklabs/kedro
  description: A Python framework for creating reproducible, maintainable and modular data science code.

extra:
  recipe-maintainers:
    - marcelotrevisani
    - yetudada
    - idanov
    - merelcht
    - AhdraMeraliQB
    - NeroOkwa
    - noklam
    - SajidAlamQB
    - lrcouto
    - DimedS
